### ISSUE TITLE
The snowboy engine should be set as "ApplyFrontend=True"

### ISSUE THREAD

**Issue by eqiihuu** [Picovoice/wake-word-benchmark#4]
Hi, I have re-run the benchmark code and get a different result from yours. According to the snowboy documentation, the snowboy engine should be set to "ApplyFront=True" when running the Alexa benchmark.
![image](https://user-images.githubusercontent.com/13514412/57158536-8c6e3480-6d98-11e9-86b6-79e17953c4c9.png)

After making the change, the snowboy engine outperform all of the other 3 engines.
![image](https://user-images.githubusercontent.com/13514412/57160635-2f757d00-6d9e-11e9-80f9-0165e629923c.png)

**Comment by kenarsa** [comment]
In order to have an apple-to-apple comparison, we decided to not set this flag as it enables audio preprocessing algorithms (e.g. automatic gain control and noise suppression) that are considered separate modules in the audio processing chain and not part of wake-word engine functionality. The other enginers (PocketSphinx and Porcupine) do not have these algorithms running in front of them.

That being said, I get your point and that an apple-to-apple comparison might not be possible. Let me think about it for a bit and if I reach this conclusion I just rather exclude Snowboy from this benchmark. The other option of putting audio frontend before PocketSphinx and Porcupine is a lot of work and also out of the scope of the wake-word engine.

**Comment by eqiihuu** [comment]
The snowboy model is tuned with the extremely simple frontend (basically just scaling). Without the frontend, this is not an apple-to-apple comparison anymore since the testing setup is quite different from the training setup. 
Actually, I have tried snowboy models with "ApplyFrontend=False" in both training and testing, and the performance is almost the same as "ApplyFrontend=False".

**Comment by kenarsa** [comment]
I don't think so. Here is the documentation: https://github.com/Kitt-AI/snowboy/blob/master/include/snowboy-detect.h#L126-L134. Also when you enable the flag it increases the CPU usage significantly. A simple scale can't increase CPU usage significantly. How do you know it is a simple scale? Do you actually have access to the source code? If yes, please share.

**Comment by kenarsa** [comment]
I decided to add enable the audio frontend option according to https://github.com/Kitt-AI/snowboy#pretrained-universal-models. I made a note in the main README about this and noted that the other engines don't have this component which puts them at a disadvantage. We also expanded the test to six different wake-words to have more comprehensive results.
